### ISSUE TITLE
Adding 'Sort By' filters to the Main Search Page

### ISSUE THREAD

**Issue by CNSConnect** [OpenCIOC/onlineresources#67]
I am working on a database focused on trails. Other trail websites provide the option for the viewer to select from various 'sort by' items as well as 'filters' to create a list based on their selections. Ie: Sort By "Trail Difficulty Rating", Trail Length, Skill Level, etc.
A couple of sites to view as examples:
vancouvertrails.com
trails.com

Can this be done?
Thanks!
~Chris

**Comment by klambacher** [comment]
I'm thinking this should be broken out into two different issues - one being the ability to change the sort order (we'll need to gather feedback to decide how to determine which fields are available for sorting) and a second to allow people to filter the results. I'll pop these out into two new issues which you can then follow.

**Comment by klambacher** [comment]
See issue #68

**Comment by CNSConnect** [comment]
I think I get the gist of your description. In my 'simple' way of
indicating what I'm particularly looking for in a search 'sort by', check
out this site:
https://www.vancouvertrails.com/trails/?details=&sort=#list


~Chris

Chris Merry
NSConnect Data and Training Coordinator
NS Trails Find A Trail Website Coordinator
Recreation Nova Scotia

chrisnsconnect@gmail.com
902.880.0775 (cell)

*Please note, I work part-time and will respond to emails within a day or
two.*

**Comment by klambacher** [comment]
Also issue #69
